#baseURL = "https://developer.elorus.com/"
#defaultContentLanguage = "en"
#disableKinds = ["taxonomy", "term", "sitemap"]
#
#[languages]
#    [languages.en]
#        weight = 4
#        languageName = "INTERNATIONAL"
#        title = "Elorus | Online Invoicing & Time Tracking Software"
#
#        [languages.en.menu]
#            [[languages.en.menu.main]]
#                name = "BLOG"
#                url = "https://www.elorus.com/blog/"
#                weight = 10
#
#            [[languages.en.menu.useful]]
#                name = "ELORUS APPLICATION"
#                title = "Login to Elorus"
#                url = "https://app.elorus.com/"
#                weight = 1
#
#            [[languages.en.menu.useful]]
#                name = "DEVELOPER API"
#                title = "Elorus API documentation"
#                url = "https://developer.elorus.com/"
#                weight = 2
#
#            [[languages.en.menu.useful]]
#                name = "SUPPORT CENTER"
#                title = "Elorus Help Center"
#                url = "https://help.elorus.com/"
#                weight = 3
#
#            [[languages.en.menu.useful]]
#                name = "BLOG"
#                title = "Avoid common mistakes and take useful advice"
#                url = "https://www.elorus.com/blog/"
#                weight = 10
#
#        [languages.en.params]
#            currency_code = "USD"
#
#            footer_cta_title = "Start with the FREE plan."
#            footer_cta_subtitle = "No credit card. No commitment."
#            footer_cta_button = "START TODAY"
#            footer_line = "♥ Carefully crafted with love."
#
#            features_integrations_title = "Elorus works with the tools you already use..."
#            features_integrations_subtitle = "Elorus integrates with your favorite applications, so you can start the timer without even switching tabs."
#            features_integrations_images = [
#                ["/integrations/jira-time-tracking", "/img/integrations/jira.svg", "Track the time you spend on Jira issues & projects"],
#                ["/integrations/asana-time-tracking", "/img/integrations/asana.svg", "Track the time you spend on Asana tasks & projects"],
#                ["/integrations/trello-time-tracking", "/img/integrations/trello.svg", "Track the time you spend on Trello cards"]
#            ]
#
#            featureTabsTitle = "Invoicing & time tracking for project-driven teams"
#
#            [[languages.en.params.featureTabs]]
#                tab_title = "Projects"
#                image = "img/features/en/thumbnail-projects.png"
#                title = "Keep your projects healthy"
#                content = "Monitor the amount of hours spent on different tasks and projects. Gain access to visualized insights into your team's performance. Get better at budget allocation by understanding the expenses and the true costs of your projects."
#                learn_more = "/tour/projects"
#
#            [[languages.en.params.featureTabs]]
#                tab_title = "Invoicing"
#                image = "img/features/en/thumbnail-invoicing-view.png"
#                title = "Invoicing made easy"
#                content = "Generate professional and customized invoices in just a few steps. No matter the country, the currency or the language of your clients; we handle it all."
#                learn_more = "/tour/invoicing"
#
#            [[languages.en.params.featureTabs]]
#                tab_title = "Time tracking"
#                image = "img/features/en/thumbnail-time-tracking-dashboard.png"
#                title = "Time tracking"
#                content = "Have a complete view of your projects. Register your project-related hours by using the time tracker or filling your weekly timesheets. Achieve the great time managementand productivity control your company needs."
#                learn_more = "/tour/time-tracking"
#
#            [[languages.en.params.featureTabs]]
#                tab_title = "Expenses"
#                image = "img/features/en/thumbnail-expenses-edit.png"
#                title = "Expense management"
#                content = "Fast and simple tracking of your company’s expenses. Supplier invoices, recurring expenses, bill payments - all at once. Expense highlight: tie expenses to your projects for optimal financial overview of your ventures."
#                learn_more = "/tour/expenses"
#
#            [[languages.en.params.featureTabs]]
#                tab_title = "Payments"
#                image = "img/features/en/thumbnail-payments-paypal.png"
#                title = "Online payments"
#                content = "Simplify the way you get paid. Accept credit cards online with PayPal, Braintree and more, without any commission towards Elorus."
#                learn_more = "/tour/billing"
#
#            [[languages.en.params.featureTabs]]
#                tab_title = "Client portal"
#                image = "img/features/en/thumbnail-client-portal-teaser.png"
#                title = "Private client portal"
#                content = "Build a strong relationship with your clients and impress them with their own, dedicated area. Using the client portal they can pay invoices online,monitor your projects as well as review their complete transaction history."
#                learn_more = "/tour/client-portal"
#
#            [[languages.en.params.featureTabs]]
#                tab_title = "Team"
#                image = "img/features/en/thumbnail-team-invite.png"
#                title = "Team productivity"
#                content = "Your accountant and partners can easily access your data whilst reducing management time and costs."
#                learn_more = "/tour/team"
#
#    [languages.el]
#        weight = 3
#        languageName = "ΕΛΛΑΔΑ"
#        title = "Elorus | Εφαρμογή Ηλεκτρονικής Τιμολόγησης & Time Tracking"
#
#        [languages.el.menu]
#            [[languages.el.menu.main]]
#                name = "BLOG"
#                url = "https://www.elorus.com/el/blog/"
#                weight = 10
#
#            [[languages.el.menu.useful]]
#                name = "ΕΦΑΡΜΟΓΗ ELORUS"
#                title = "Είδοδος στο Elorus"
#                url = "https://app.elorus.com/"
#                weight = 1
#
#            [[languages.el.menu.useful]]
#                name = "DEVELOPER API"
#                title = "Τεχνική τεκμηρίωση προγραμματιστικού API"
#                url = "https://developer.elorus.com/"
#                weight = 2
#
#            [[languages.el.menu.useful]]
#                name = "ΚΕΝΤΡΟ ΥΠΟΣΤΗΡΙΞΗΣ"
#                title = "Κέντρο υποστήριξης Elorus"
#                url = "https://help.elorus.com/gr"
#                weight = 4
#
#            [[languages.el.menu.useful]]
#                name = "BLOG"
#                title = "Διαβάσε ενδιαφέροντα άρθρα για τα οικονομικά της επιχείρησής σας"
#                url = "https://www.elorus.com/el/blog/"
#                weight = 15
#
#        [languages.el.params]
#            currency_code = "EUR"
#
#            footer_cta_title = "Ξεκίνα σήμερα με το ΔΩΡΕΑΝ πλάνο!"
#            footer_cta_subtitle = "Χωρίς κάρτα, χωρίς καμία δέσμευση."
#            footer_cta_button = "ΔΗΜΙΟΥΡΓΙΑ ΔΩΡΕΑΝ ΛΟΓΑΡΙΑΣΜΟΥ"
#            footer_line = "♥ Carefully crafted with love."
#
#            features_integrations_title = "To Elorus δουλεύει με τα εργαλεία που ήδη χρησιμοποιείς!"
#            features_integrations_subtitle = "Το Elorus δίνει το παρόν στις αγαπημένες σου εφαρμογές! Έτσι, μπορείς να ξεκινήσεις τον χρονομετρητή χωρίς καν να αλλάξεις περιβάλλον εργασίας."
#            features_integrations_images = [
#                ["/integrations/jira-time-tracking", "/img/integrations/jira.svg", "Παρακολούθησε το χρόνο που εργάζεσαι σε Jira issues & projects"],
#                ["/integrations/asana-time-tracking", "/img/integrations/asana.svg", "Παρακολούθησε το χρόνο που εργάζεσαι σε Asana tasks & projects"],
#                ["/integrations/trello-time-tracking", "/img/integrations/trello.svg", "Παρακολούθησε το χρόνο που εργάζεσαι σε Trello cards"]
#            ]
#
#            featureTabsTitle = "Ηλεκτρονική τιμολόγηση & χρονοχρέωση για ομάδες και επιχειρήσεις"
#
#            [[languages.el.params.featureTabs]]
#                tab_title = "Έργα"
#                image = "img/features/el/thumbnail-projects.png"
#                title = "Μεγιστοποίησε τα κέρδη των έργων σου"
#                content = "Παρακολούθησε τις ώρες που ξοδεύεις σε έργα και εργασίες. Απόκτησε πρόσβαση σε γραφικές αναφορές για την απόδοση της ομάδας σου. Κατανόησε τα έξοδα και τα πραγματικά κόστη των έργων σου και βελτιστοποίησε την κοστολόγησή σου."
#                learn_more = "/tour/projects"
#
#            [[languages.el.params.featureTabs]]
#                tab_title = "Ηλεκτρονική τιμολόγηση"
#                image = "img/features/el/thumbnail-invoicing-view.png"
#                title = "Ηλεκτρονική τιμολόγηση"
#                content = "Δημιούργησε επαγγελματικά τιμολόγια, προσαρμοσμένα στις ανάγκες σας. Δεν έχει σημασία η χώρα, το νόμισμα ή η γλώσσα των πελατών σου. Το Elorus τα υποστηρίζει όλα!"
#                learn_more = "/tour/invoicing"
#
#            [[languages.el.params.featureTabs]]
#                tab_title = "Time tracking"
#                image = "img/features/el/thumbnail-time-tracking-dashboard.png"
#                title = "Χρονοκαταγραφή & χρονοχρέωση"
#                content = "Έχε μια ολοκληρωμένη οπτική των έργων σου. Κατάγραψε τις ώρες των έργων που αναλαμβάνεις, είτε μετρώντας τον χρόνο σου, είτε συμπληρώνοντας τα εβδομαδιαία timesheets. Μάθε να διαχειρίζεσαι το χρόνο και έλεγξε την παραγωγικότητα της επιχείρησης σου."
#                learn_more = "/tour/time-tracking"
#
#            [[languages.el.params.featureTabs]]
#                tab_title = "Έξοδα"
#                image = "img/features/el/thumbnail-expenses-edit.png"
#                title = "Διαχείριση εξόδων"
#                content = "Παρακολούθησε τα έξοδα της εταιρείας σου με ευκολία. Δαπάνες, επαναλαμβανόμενα έξοδα, πληρωμές λογαριασμών - όλα σε μια πλατφόρμα. Σύνδεσε έξοδα με τα έργα σου για τον βέλτιστο οικονομικό έλεγχο της επιχείρησης σου."
#                learn_more = "/tour/expenses"
#
#            [[languages.el.params.featureTabs]]
#                tab_title = "Πληρωμές"
#                image = "img/features/el/thumbnail-payments-vivawallet.png"
#                title = "Online πληρωμές"
#                content = "Λάβε πληρωμές πιο εύκολα και γρήγορα! Ξεκίνα να δέχεσαι πληρωμές με κάρτες online, μέσω VivaWallet, PayPal, Braintree κ.ά., χωρίς καμία προμήθεια προς το Elorus."
#                learn_more = "billing"
#
#            [[languages.el.params.featureTabs]]
#                tab_title = "Client portal"
#                image = "img/features/el/thumbnail-client-portal-teaser.png"
#                title = "Ασφαλής περιοχή πελάτη"
#                content = "Δημιούργησε μια ισχυρή σχέση με τους πελάτες σου και εντυπωσίασε τους με το client portal του Elorus. Προσφορές, online εξόφληση τιμολογίων, ιστορικό συναλλαγών σε ένα ασφαλές και εύχρηστο περιβάλλον."
#                learn_more = "/tour/client-portal"
#
#            [[languages.el.params.featureTabs]]
#                tab_title = "Ομάδα"
#                image = "img/features/el/thumbnail-team-invite.png"
#                title = "Λογιστής και συνεργάτες"
#                content = "Προσκάλεσε τον λογιστή και τους συνεργάτες σου στο Elorus! Όρισε εσύ σε ποια δεδομένα επιθυμείς να έχουν πρόσβαση και εξοικονόμησε πολύτιμο χρόνο και κόστη διαχείρισης."
#                learn_more = "/tour/team"
#
#
#[markup]
#  [markup.tableOfContents]
#    endLevel = 2
#    ordered = false
#    startLevel = 2
